# Generated by Django 5.2.7 on 2026-01-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchamodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
